name: Ethereum Worker

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Upload Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build and pack Ethereum worker binary with libs
        run: make pack-release

      - name: Set ref vars
        id: refs
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.refs.outputs.SOURCE_TAG }}
          release_name: "Release ${{ steps.refs.outputs.SOURCE_TAG }}"
          draft: false
          prerelease: false

      - name: Upload release
        id: upload-release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ethereum-worker.zip
          asset_name: ethereum-worker.zip
          asset_content_type: application/zip
